// Generated by gencpp from file my_robot_msgs/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_ADDTWOINTS_H
#define MY_ROBOT_MSGS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <my_robot_msgs/AddTwoIntsRequest.h>
#include <my_robot_msgs/AddTwoIntsResponse.h>


namespace my_robot_msgs
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace my_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_msgs::AddTwoInts > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::my_robot_msgs::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::my_robot_msgs::AddTwoInts > {
  static const char* value()
  {
    return "my_robot_msgs/AddTwoInts";
  }

  static const char* value(const ::my_robot_msgs::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_msgs::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::my_robot_msgs::AddTwoInts >
template<>
struct MD5Sum< ::my_robot_msgs::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::my_robot_msgs::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::AddTwoIntsRequest> should match
// service_traits::DataType< ::my_robot_msgs::AddTwoInts >
template<>
struct DataType< ::my_robot_msgs::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::my_robot_msgs::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_msgs::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::my_robot_msgs::AddTwoInts >
template<>
struct MD5Sum< ::my_robot_msgs::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::my_robot_msgs::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::AddTwoIntsResponse> should match
// service_traits::DataType< ::my_robot_msgs::AddTwoInts >
template<>
struct DataType< ::my_robot_msgs::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::my_robot_msgs::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_ADDTWOINTS_H
