// Generated by gencpp from file my_robot_msgs/fibonacciResponse.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_FIBONACCIRESPONSE_H
#define MY_ROBOT_MSGS_MESSAGE_FIBONACCIRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct fibonacciResponse_
{
  typedef fibonacciResponse_<ContainerAllocator> Type;

  fibonacciResponse_()
    : result()  {
    }
  fibonacciResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> const> ConstPtr;

}; // struct fibonacciResponse_

typedef ::my_robot_msgs::fibonacciResponse_<std::allocator<void> > fibonacciResponse;

typedef boost::shared_ptr< ::my_robot_msgs::fibonacciResponse > fibonacciResponsePtr;
typedef boost::shared_ptr< ::my_robot_msgs::fibonacciResponse const> fibonacciResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::fibonacciResponse_<ContainerAllocator1> & lhs, const ::my_robot_msgs::fibonacciResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::fibonacciResponse_<ContainerAllocator1> & lhs, const ::my_robot_msgs::fibonacciResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67cdd51ca1859f10c723484b0bc5b1b6";
  }

  static const char* value(const ::my_robot_msgs::fibonacciResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67cdd51ca1859f10ULL;
  static const uint64_t static_value2 = 0xc723484b0bc5b1b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/fibonacciResponse";
  }

  static const char* value(const ::my_robot_msgs::fibonacciResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] result\n"
;
  }

  static const char* value(const ::my_robot_msgs::fibonacciResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fibonacciResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::fibonacciResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::fibonacciResponse_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_FIBONACCIRESPONSE_H
