// Generated by gencpp from file my_robot_msgs/fibonacci.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_FIBONACCI_H
#define MY_ROBOT_MSGS_MESSAGE_FIBONACCI_H

#include <ros/service_traits.h>


#include <my_robot_msgs/fibonacciRequest.h>
#include <my_robot_msgs/fibonacciResponse.h>


namespace my_robot_msgs
{

struct fibonacci
{

typedef fibonacciRequest Request;
typedef fibonacciResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct fibonacci
} // namespace my_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_msgs::fibonacci > {
  static const char* value()
  {
    return "226a58bba76a1d92514e474f2bb7bc3b";
  }

  static const char* value(const ::my_robot_msgs::fibonacci&) { return value(); }
};

template<>
struct DataType< ::my_robot_msgs::fibonacci > {
  static const char* value()
  {
    return "my_robot_msgs/fibonacci";
  }

  static const char* value(const ::my_robot_msgs::fibonacci&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_msgs::fibonacciRequest> should match
// service_traits::MD5Sum< ::my_robot_msgs::fibonacci >
template<>
struct MD5Sum< ::my_robot_msgs::fibonacciRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::fibonacci >::value();
  }
  static const char* value(const ::my_robot_msgs::fibonacciRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::fibonacciRequest> should match
// service_traits::DataType< ::my_robot_msgs::fibonacci >
template<>
struct DataType< ::my_robot_msgs::fibonacciRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::fibonacci >::value();
  }
  static const char* value(const ::my_robot_msgs::fibonacciRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_msgs::fibonacciResponse> should match
// service_traits::MD5Sum< ::my_robot_msgs::fibonacci >
template<>
struct MD5Sum< ::my_robot_msgs::fibonacciResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::fibonacci >::value();
  }
  static const char* value(const ::my_robot_msgs::fibonacciResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::fibonacciResponse> should match
// service_traits::DataType< ::my_robot_msgs::fibonacci >
template<>
struct DataType< ::my_robot_msgs::fibonacciResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::fibonacci >::value();
  }
  static const char* value(const ::my_robot_msgs::fibonacciResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_FIBONACCI_H
